# Change these first
owner: cruzasesorjuridico # Your GitHub organization or username, where this repository lives
repo: estado # The name of this repository

sites:
  - name: Web Principal
    url: https://cruzasesorjuridico.com
  - name: Tienda
    url: https://tienda.cruzasesorjuridico.com
  - name: Videollamadas para clientes
    url: https://clientes.cruzasesorjuridico.com

status-website:
  theme: ocean
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: estado.cruzasesorjuridico.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Web de estado de los servicios de cruzasesorjuridico.com"
  introMessage: 
  navbar:
    - title: Estado
      href: /
    - title: Github
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
